-- WK5 Homework
-- QUESTION 1
select CUSTOMER.FIRST_NAME, CUSTOMER.LAST_NAME, COUNTRY, CITY.CITY
from CUSTOMER 
full join ADDRESS 
on CUSTOMER.ADDRESS_ID = ADDRESS.address_id
full join city
on ADDRESS.CITY_ID = CITY.city_id 
full join COUNTRY
on CITY.COUNTRY_ID = COUNTRY.country_id
where COUNTRY = 'United States'
-- ANSWER; 4

-- QUESTION 2
select FIRST_NAME, LAST_NAME, AMOUNT
from customer
inner join PAYMENT
on CUSTOMER.CUSTOMER_ID = PAYMENT.CUSTOMER_ID
where AMOUNT >= 6.99
-- ANSWER; 2438

-- QUESTION 3
select CUSTOMER.FIRST_NAME, CUSTOMER.LAST_NAME
from PAYMENT
inner join CUSTOMER
on CUSTOMER.CUSTOMER_ID = PAYMENT.CUSTOMER_ID
group by CUSTOMER.FIRST_NAME, CUSTOMER.LAST_NAME
having SUM(AMOUNT) >= 175
order by SUM(AMOUNT) desc;
-- ANSWER; 7

-- QUESTION 4
select CUSTOMER.FIRST_NAME, CUSTOMER.LAST_NAME, COUNTRY, CITY.CITY
from CUSTOMER 
full join ADDRESS 
on CUSTOMER.ADDRESS_ID = ADDRESS.address_id
full join city
on ADDRESS.CITY_ID = CITY.city_id 
full join COUNTRY
on CITY.COUNTRY_ID = COUNTRY.country_id
where COUNTRY = 'Nepal'
-- ANSWER; 1
-- NOT SURE IF NEPAL WAS MEANT TO BE USED AS A CITY BUT DOWN BELOW
select CUSTOMER.FIRST_NAME, CUSTOMER.LAST_NAME, CITY.CITY
from CUSTOMER 
full join ADDRESS 
on CUSTOMER.ADDRESS_ID = ADDRESS.address_id
full join city
on ADDRESS.CITY_ID = CITY.city_id 
-- ANSWER; 0

-- QUESTION 5
select STAFF.FIRST_NAME, STAFF.LAST_NAME, AMOUNT
from PAYMENT, STAFF
group by STAFF.STAFF_ID, PAYMENT.AMOUNT
order by SUM(AMOUNT) desc;
-- ANSWER; TIE JON & MIKE

-- QUESTION 6
select FILM.RATING 
from FILM 
where FILM.RATING = 'NC-17';
-- ANSWER; 178 FOR G RATED, 194 FOR PG RATED...
-- 223 FOR PG-13 RATED, 195 FOR R RATED, 210 FOR NC-17 RATED

-- QUESTION 7
select STORE_ID, FIRST_NAME, LAST_NAME
from CUSTOMER 
where CUSTOMER_ID in (
	select CUSTOMER_ID 
	from PAYMENT 
	where PAYMENT.AMOUNT >= 6.99
);

-- QUESTION 8 
select STORE_ID
from RENTAL, STORE 
where RENTAL_ID in (
	select RENTAL_ID 
	from PAYMENT 
	group by RENTAL_ID
	having SUM(AMOUNT) = 0
);
-- ANSWER; 48 



